name: Douyu_Gift

on:
  push:
    branches:
      - master
  workflow_dispatch: 
  schedule:
    - cron: '10 16 * * *'
  watch:
    types: [started]

jobs:
  dy_auto_donate_helper:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: pip install -r requirements.txt
      - name: 'Working'
        env:
          SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
          COOKIES: ${{ secrets.COOKIES }}
        run: |
          python main.py
