name: Douyu

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
  schedule:
    - cron: "10 16 * * *"
  watch:
    types: [started]

jobs:
  douyu_donate:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Set up Nodejs"
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: "Install requirements"
        run: npm install
      - name: "Build TypeScript"
        run: npx tsc
      - name: "Create ENV File"
        run: |
          touch .env
          cat > .env << EOF
          CF_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }}
          CF_NAMESPACE_ID=${{ secrets.CF_NAMESPACE_ID }}
          CF_API_TOKEN=${{ secrets.CF_API_TOKEN }}
          EOF
      - name: "Working"
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_NAMESPACE_ID: ${{ secrets.CF_NAMESPACE_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          node ./dist/main.js
